
export const screenAssets = {
    logoScreen: {
        images: [
            require("@/assets/Logo/FCOH_without_50mt.png"),
        ],
    },
    intro: {
        svgs: [
            require("@/assets/Skull_and_crossbones.svg"),
        ],
    },
    mainMenu: {
        images: [
            require("@/assets/Menus/plumMarble4.png"),
            require("@/assets/Menus/darkSlate1.png"),
        ],
        fonts: [
            { family: 'Metal Mania', url: require("@/assets/fonts/MetalMania-Regular.ttf") },
            { family: 'Cinzel Decorative', url: require("@/assets/fonts/CinzelDecorative-Regular.ttf")},
        ],
        audio: [
            require("@/music/main_menu.mp3"),
        ],
    },
    buildTeam: {
        images: [
            require("@/assets/CombatantModels/Witch_recolor.png"),
            require("@/assets/CombatantModels/Hunter_recolor.png"),
            require("@/assets/CombatantModels/Vanguard_recolor.png"),
            require("@/assets/CombatantModels/Defender_blue_p10.png"),
            require("@/assets/CombatantModels/Defender_red_p10.png"),
            require("@/assets/CombatantModels/Wizard1.png"),
            require("@/assets/CombatantModels/Wizard_resize_recolor.png"),
            require("@/assets/CombatantModels/Rogue_recolor.png"),
            require("@/assets/CombatantModels/FistWeaver_recolor.png"),
            require("@/assets/CombatantModels/Fool_blue_p10.png"),
            require("@/assets/CombatantModels/Fool_red_p10.png"),
            require("@/assets/CombatantModels/Artificer_blue.png"),
            require("@/assets/CombatantModels/Artificer_red.png"),
            require("@/assets/CombatantModels/Healer_recolor.png"),
            require("@/assets/CombatantModels/captain_recolor.png"),
            require("@/assets/CombatantModels/Pikeman_blue_p10.png"),
            require("@/assets/CombatantModels/Pikeman_red_p10.png"),
            
        ],
        svgs: [
            require("@/assets/Slash.svg"),
            require("@/assets/crush.png"),
            require("@/assets/Pierce.svg"),
            require("@/assets/Flame.svg"),
            require("@/assets/Ice.svg"),
            require("@/assets/Thunder.svg"),
            require("@/assets/Skull.svg"),
            require("@/assets/Sun.svg"),
            require("@/assets/Pentagram.svg"),
            require("@/assets/Healing.svg"),
            require("@/assets/Unstoppable.svg"),

        ],
        audio: [
            require("@/music/build_team_full.mp3"),
        ],
    },
    journey: {
        images: [
            require("@/assets/Backgrounds/Swirl2.png"),
            require("@/assets/Backgrounds/LessDarkStone3.png"),
            require("@/assets/Backgrounds/cave3.png"),
            require("@/assets/Backgrounds/simpleLand5.png"),
            require("@/assets/Backgrounds/temple10.png"),
        ],
        audio: [
            require("@/music/journey.mp3"),
        ],
    },
    match: {
        images: [
            require("@/assets/Frames/darkFrame4.png"),
            require("@/assets/Frames/jungleFrame.png"),
            require("@/assets/Frames/menuFrame3.png"),
            require("@/assets/Frames/templeFrame4.png"),
            require("@/assets/CombatantModels/Troll.png"),
            require("@/assets/CombatantModels/OozeGolem.png"),
            require("@/assets/CombatantModels/WeaveEater.png"),
            require("@/assets/statusIcons/TUTOR.png"),
            require('@/assets/Crush2.png'),
            require("@/assets/CombatantModels/Ballista_Up.png"),
            require("@/assets/CombatantModels/Ballista_Down.png"),
            require("@/assets/CombatantModels/Blue_Bomb.png"),
            require("@/assets/CombatantModels/Red_Bomb.png"),
            require("@/assets/CombatantModels/BlueDeathTower.png"),
            require("@/assets/CombatantModels/RedDeathTower.png"),

            require("@/assets/CombatantModels/blue_brick.png"),
            require("@/assets/CombatantModels/Goblin_no_back.png")
        ],
        svgs: [
           require("@/assets/statusIcons/ARCANE_CHANNELING.svg"),
           require("@/assets/statusIcons/FOCUS_AIM.svg"),
           require("@/assets/statusIcons/BLOCKING_STANCE.svg"),
           require("@/assets/statusIcons/FORTIFIED.svg"),
           require("@/assets/statusIcons/REGENERATING.svg"),
           require("@/assets/statusIcons/IMMOBILIZED.svg"),
           require("@/assets/statusIcons/FROZEN.svg"),
           require("@/assets/statusIcons/POISONED.svg"),
           require("@/assets/statusIcons/MOBILITY_BOOST.svg"),
           require("@/assets/statusIcons/STRENGTH_BOOST.svg"),
           require("@/assets/statusIcons/ENCOURAGED.svg"),
           require("@/assets/statusIcons/RALLIED.svg"),
           require("@/assets/statusIcons/STRENGTH_DOWNGRADE.svg"),
           require("@/assets/statusIcons/BLEEDING.svg"),
           require("@/assets/statusIcons/LUCK_DOWNGRADE.svg"),
           require("@/assets/statusIcons/SLOW.svg"),
           require("@/assets/statusIcons/INSPIRING_KILLER.svg"),
           require("@/assets/statusIcons/FOOLS_LUCK.svg"),
           require("@/assets/statusIcons/TAUNTED.svg"),
           require("@/assets/statusIcons/MESMERIZING.svg"),
           require("@/assets/statusIcons/MESMERIZED.svg"),
           require("@/assets/statusIcons/NAUSEATED.svg"),
           require("@/assets/statusIcons/STUPEFIED.svg"),
           require("@/assets/statusIcons/STAGGERED.svg"),
           require("@/assets/statusIcons/FIRST_STRIKE.svg"),
           require("@/assets/statusIcons/DEFENSE_DOWNGRADE.svg"),
           require("@/assets/statusIcons/IDAI_NO_HADOU.svg"),
           require("@/assets/statusIcons/CLOAKED.svg"),
           require("@/assets/statusIcons/FULL_METAL_JACKET.svg"),
           require("@/assets/statusIcons/DIVINE_MIRACLE.svg"),
           require("@/assets/statusIcons/PANIC.svg"),
           require("@/assets/statusIcons/PLAGUED.svg"),
           require("@/assets/statusIcons/BURNING.svg"),
           require("@/assets/statusIcons/LIFE_DRINKER.svg"),
           require("@/assets/statusIcons/CHARMED.svg"),
           require("@/assets/statusIcons/ARCANE_OVERCHARGE.svg"),
           require("@/assets/statusIcons/ARCANE_BARRIER.svg"),
           require("@/assets/statusIcons/ARCANE_CONDUIT.svg"),
           require("@/assets/statusIcons/DIVINE_RETRIBUTION.svg"),
           require("@/assets/statusIcons/SANCTUARY.svg"),
           require("@/assets/statusIcons/SLEEPING.svg"),
           require("@/assets/statusIcons/RELOAD.svg"),
           require("@/assets/statusIcons/INGENIOUS_UPGRADE.svg"),
           require("@/assets/statusIcons/CIRCUS_DIABOLIQUE.svg"),
           require("@/assets/statusIcons/NIGHTMARE_LOCKED.svg"),
           require("@/assets/statusIcons/DIAMOND_HOOKED.svg"),
           require("@/assets/statusIcons/DIAMOND_HOOKED_HOLDING.svg"),
           require("@/assets/statusIcons/GOING_OFF.svg"),
           require("@/assets/statusIcons/SURPRISE_BOOM.svg"),
           require("@/assets/statusIcons/RIPOSTE.svg"),
           require("@/assets/statusIcons/DECOY.svg"),
           require("@/assets/statusIcons/MARKED_FOR_PAIN.svg"),
           require("@/assets/statusIcons/MARKED_FOR_EXECUTION.svg"),
           require("@/assets/statusIcons/MARKED_FOR_OBLIVION.svg"),
           require("@/assets/statusIcons/DEFENDING.svg"),
           require("@/assets/statusIcons/FORBIDDEN_AFFLICTION.svg"),
           require("@/assets/statusIcons/MARCHING_DEFENSE.svg"),
           require("@/assets/statusIcons/GUARDIAN.svg"),
           require("@/assets/statusIcons/GUARDIAN_PROTECTED.svg"),
           require("@/assets/statusIcons/SHIELD_WALL.svg"),
           require("@/assets/statusIcons/SHIELD_WALL_PROTECTED.svg"),
           require("@/assets/statusIcons/SADIST.svg"),
           require("@/assets/statusIcons/ARCANE_SHIELD_WALL.svg"),
           require("@/assets/statusIcons/ARCANE_SHIELD_WALL_PROTECTED.svg"),
           require("@/assets/statusIcons/FRENZY.svg"),
           require("@/assets/statusIcons/DIVINE_ALACRITY.svg"),

           require("@/assets/statusIcons/LIGHTNING.svg"),
           require("@/assets/statusIcons/SLASH.svg"),
           require("@/assets/statusIcons/PIERCE.svg"),
           require("@/assets/statusIcons/HOLY.svg"),
           
           require("@/assets/Ballista.svg"),
           require("@/assets/Wall.svg"),
           require("@/assets/Bomb.svg"),
           require("@/assets/Babel.svg"),
           require("@/assets/ACHILLES.svg"),
           
           require("@/assets/CombatantModels/PierceTarget.svg"),
           require("@/assets/CombatantModels/NormalTarget.svg"),
           require("@/assets/CombatantModels/CritTarget.svg"),
           require("@/assets/CombatantModels/BlockTarget.svg"),
           require("@/assets/CombatantModels/FireTarget.svg"),
           require("@/assets/CombatantModels/IceTarget.svg"),
           require("@/assets/CombatantModels/LightningTarget.svg"),
           require("@/assets/CombatantModels/BlightTarget.svg"),

        ],
        audio: [
            require("@/music/tutorial.mp3"),
            require("@/music/easy_combat.mp3"),
            require("@/music/normal_combat.mp3"),
            require("@/music/hard_combat.mp3"),
            require("@/music/boss_combat.mp3"),
        ],
    },
    postMatch: {
        audio: [
            require("@/music/victory.mp3"),
            require("@/music/game_over.mp3"),
        ],
    },
}
