
export enum SoundByte {
    // damage
    Blight,
    CRUSH,
    DARK,
    FIRE,
    HEALING,
    HOLY,
    ICE,
    PIERCE,
    SLASH,
    LIGHTNING,

    BUFF,
    DEBUFF,
    HOLY_BUFF,

    // round start
    TURN_START,

    FOOL_LAUGH,
    FOOL_LAUGH_FASTER,
    EVIL_LAUGH,
    SCREAM,
    SNORING,
    MISS,

    SEDUCE,
    ARMOR,
    SMITH,
    COUGH,
    AIM,
    SHADOW_STEP,
    RAGE,
    ARCANE,

    FOREST_WALK1,
    FOREST_WALK2,
    FOREST_WALK3,
    CAVE_WALK1,
    CAVE_WALK2,
    CAVE_WALK3,
    STONE_WALK1,
    STONE_WALK2,

    DEFEAT_SOUND,
    VICTORY_SOUND,
    
    MENU_BUTTON_CLICK,
    ACTION_BUTTON_CLICK,
    CANCEL,
    WRITING,
    MENU_SCROLL,
    // MENU_SCROLL_MINOR,
    SKILL_SELECT,
    CHECKBOX_CHECK,
    TOWER_TRAVERSAL,
    TOWER_ASCEND,
    PROMPT,



    DEFENDER_SELECT,
    CHAMPION_SELECT,
    VANGUARD_SELECT,
    WIZARD_SELECT,
    WITCH_SELECT,
    PIKEMAN_SELECT,
    HUNTER_SELECT,
    FIST_WEAVER_SELECT,
    HEALER_SELECT,
    ROGUE_SELECT,
    ARTIFICER_SELECT,

    WELCOME_TO_DIE_FOR_ME,
    CHOOSE_YOUR_JOURNEY
}

export enum Track {
    MAIN_MENU,
    BUILD_TEAM,
    JOURNEY,
    TUTORIAL_FIGHT_THEME,
    EASY_FIGHT_THEME,
    MEDIUM_FIGHT_THEME,
    HARD_FIGHT_THEME,
    BOSS_FIGHT_THEME,
    GAME_OVER,
    VICTORY,
    // CREDITS
}