export enum CombatantType {
    Militia = "Militia",
    Defender = "Defender", 
    Hunter = "Hunter",
    Healer = "Healer",
    Wizard = "Wizard",
    StandardBearer = "StandardBearer",
    Witch = "Witch",
    Fool = "Fool",
    Pikeman = "Pikeman",
    Vanguard = "Vanguard",
    Rogue = "Rogue",
    Artificer = "Artificer",
    Fistweaver = "Fistweaver",
}
