export enum CombatantType {
    Militia = "Militia",
    Defender = "Defender", 
    Hunter = "Hunter",
    Healer = "Healer",
    Wizard = "Wizard",
    StandardBearer = "Standard Bearer",
    Witch = "Witch",
    Fool = "Fool",
    Pikeman = "Pikeman",
    Vanguard = "Vanguard",
    Rogue = "Rogue",
    Artificer = "Artificer",
    FistWeaver = "Fistweaver",
    Gorilla = "Gorilla",
    BallistaTurret = "Ballista Turret",
    Myrmidon = "Myrmidon",
    Iskariot = "Iskariot",
    DragonOfChaos = "Dragon of Chaos",

    Wall = "Wall",
    Bomb = "Bomb",
}
